<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-blue-600">Operations board</p><h1 class="mt-1 text-2xl font-semibold tracking-tight">Create {{ auth()->user()->company?->settings?->operation_label_singular ?? 'delivery' }}</h1><p class="mt-1 text-sm text-slate-500">Create the work record first; assign active personnel afterward.</p></div></x-slot>

    @if ($customers->isEmpty())
        <section class="max-w-2xl rounded-2xl border border-amber-200 bg-amber-50 p-7"><h2 class="font-semibold text-amber-950">Add a customer first</h2><p class="mt-2 text-sm text-amber-800">Every delivery belongs to a company-scoped customer record.</p><a href="{{ route('tenant.customers.index') }}" class="mt-5 inline-flex rounded-xl bg-amber-900 px-4 py-3 text-sm font-semibold text-white">Open customers</a></section>
    @else
        <form method="POST" action="{{ route('tenant.deliveries.store') }}" class="max-w-4xl space-y-6">
            @csrf
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">Customer and schedule</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-semibold">Customer</label><select name="customer_id" required class="mt-2 w-full rounded-xl border-slate-300 focus:border-blue-500 focus:ring-blue-500">@foreach ($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id') == $customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div><label class="text-sm font-semibold">Reference <span class="font-normal text-slate-400">optional</span></label><input name="reference" value="{{ old('reference') }}" placeholder="Auto-generated if blank" class="mt-2 w-full rounded-xl border-slate-300 focus:border-blue-500 focus:ring-blue-500"></div><div><label class="text-sm font-semibold">Scheduled time <span class="font-normal text-slate-400">optional</span></label><input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at') }}" class="mt-2 w-full rounded-xl border-slate-300 focus:border-blue-500 focus:ring-blue-500"></div></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">Pickup and drop-off</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-semibold">Pickup address</label><textarea required name="pickup_address" rows="4" class="mt-2 w-full rounded-xl border-slate-300 focus:border-blue-500 focus:ring-blue-500">{{ old('pickup_address') }}</textarea></div><div><label class="text-sm font-semibold">Drop-off address</label><textarea required name="dropoff_address" rows="4" class="mt-2 w-full rounded-xl border-slate-300 focus:border-blue-500 focus:ring-blue-500">{{ old('dropoff_address') }}</textarea></div><div><label class="text-sm font-semibold">Pickup contact <span class="font-normal text-slate-400">optional</span></label><input name="pickup_contact_name" value="{{ old('pickup_contact_name') }}" class="mt-2 w-full rounded-xl border-slate-300"><input name="pickup_contact_phone" value="{{ old('pickup_contact_phone') }}" placeholder="Phone" class="mt-3 w-full rounded-xl border-slate-300"></div><div><label class="text-sm font-semibold">Drop-off contact <span class="font-normal text-slate-400">optional</span></label><input name="dropoff_contact_name" value="{{ old('dropoff_contact_name') }}" class="mt-2 w-full rounded-xl border-slate-300"><input name="dropoff_contact_phone" value="{{ old('dropoff_contact_phone') }}" placeholder="Phone" class="mt-3 w-full rounded-xl border-slate-300"></div><div class="sm:col-span-2"><label class="text-sm font-semibold">Operational notes <span class="font-normal text-slate-400">optional</span></label><textarea name="notes" rows="3" class="mt-2 w-full rounded-xl border-slate-300">{{ old('notes') }}</textarea></div></div></section>
            <div class="flex justify-end gap-3"><a href="{{ route('tenant.deliveries.index') }}" class="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">Create delivery</button></div>
        </form>
    @endif
</x-app-layout>
